2023-01-30 17:50:44,691 INFO    ======================================================================
2023-01-30 17:50:44,692 INFO    Survey 130, for Ouro Preto, Minas Gerais
2023-01-30 17:50:44,693 INFO    Searching by bounding box, max_zoom=24
2023-01-30 17:50:44,694 INFO    ----------------------------------------------------------------------
2023-01-30 17:50:44,694 INFO    Rectangle calculated: [-20.2519, -43.4372, -20.5229, -43.7846]
2023-01-30 17:50:44,695 INFO    Searching rectangle: zoom factor = 0, node = []
2023-01-30 17:50:45,246 WARNING HTTP status 403 from web site: IP address blocked. Waiting 0.1 minutes.
2023-01-30 17:50:51,970 WARNING HTTP status 403 from web site: IP address blocked. Waiting 0.1 minutes.
2023-01-30 17:51:00,993 ERROR   Exception in get_search_page_info_rectangle
Traceback (most recent call last):
  File "C:\mono\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\mono\airbnb-data-collection\airbnb_listing.py", line 331, in __insert
    cur.execute(sql, insert_args)
psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type double precision: "17 USD"
LINE 12:                 2, 1, 1.0, '17 USD', 0, 1,  -20.396086712401...
                                    ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\mono\airbnb-data-collection\airbnb_survey.py", line 819, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\mono\airbnb-data-collection\airbnb_listing.py", line 167, in save
    self.config.connection.conn.rollback()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'conn'
2023-01-30 17:51:00,997 ERROR   Error in recurse_quadtree
Traceback (most recent call last):
  File "C:\mono\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\mono\airbnb-data-collection\airbnb_listing.py", line 331, in __insert
    cur.execute(sql, insert_args)
psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type double precision: "17 USD"
LINE 12:                 2, 1, 1.0, '17 USD', 0, 1,  -20.396086712401...
                                    ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\mono\airbnb-data-collection\airbnb_survey.py", line 534, in recurse_quadtree
    (zoomable, median_leaf) = self.search_node(
                              ^^^^^^^^^^^^^^^^^
  File "C:\mono\airbnb-data-collection\airbnb_survey.py", line 819, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\mono\airbnb-data-collection\airbnb_listing.py", line 167, in save
    self.config.connection.conn.rollback()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'conn'
2023-01-30 17:51:01,001 ERROR   Error
Traceback (most recent call last):
  File "C:\mono\airbnb-data-collection\airbnb_listing.py", line 157, in save
    self.__insert()
  File "C:\mono\airbnb-data-collection\airbnb_listing.py", line 331, in __insert
    cur.execute(sql, insert_args)
psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type double precision: "17 USD"
LINE 12:                 2, 1, 1.0, '17 USD', 0, 1,  -20.396086712401...
                                    ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\mono\airbnb-data-collection\airbnb_survey.py", line 472, in search
    self.recurse_quadtree(quadtree_node, median_node, None, flag)
  File "C:\mono\airbnb-data-collection\airbnb_survey.py", line 534, in recurse_quadtree
    (zoomable, median_leaf) = self.search_node(
                              ^^^^^^^^^^^^^^^^^
  File "C:\mono\airbnb-data-collection\airbnb_survey.py", line 819, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\mono\airbnb-data-collection\airbnb_listing.py", line 167, in save
    self.config.connection.conn.rollback()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'conn'
